# Generated by Django 4.2.7 on 2025-10-03 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content to analyze')),
                ('url', models.URLField(blank=True, help_text='Optional URL source', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('seo_score', models.IntegerField(blank=True, help_text='SEO score 0-100', null=True)),
                ('keyword_density', models.JSONField(blank=True, help_text='Top keywords', null=True)),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, help_text='AI recommendations')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='analyzer_co_created_133d61_idx'), models.Index(fields=['status'], name='analyzer_co_status_21be52_idx')],
            },
        ),
    ]
